# Generated by Django 4.1.3 on 2022-11-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("effective_cost", models.FloatField()),
                ("credit_cost", models.FloatField()),
                ("initial_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("payment_date", models.DateField()),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
            },
        ),
        migrations.CreateModel(
            name="PaymentAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dues_number", models.IntegerField()),
                ("balance", models.FloatField()),
            ],
            options={
                "verbose_name": "Convenio de Pago",
                "verbose_name_plural": "Convenios de Pagos",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_names", models.CharField(max_length=150)),
                ("first_names", models.CharField(max_length=150)),
                ("identification", models.CharField(max_length=13)),
                ("cellphone", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=150)),
            ],
            options={
                "verbose_name": "Estudiante",
                "verbose_name_plural": "Estudiantes",
            },
        ),
    ]
