# Generated by Django 4.1.3 on 2022-11-27 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mensualidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Nombre de la Cohorte"
                    ),
                ),
                ("initial_date", models.DateField(verbose_name="Fecha de Inicio")),
                ("end_date", models.DateField(verbose_name="Fecha fin")),
                ("effective_cost", models.FloatField(verbose_name="Costo en efectivo")),
                ("credit_cost", models.FloatField(verbose_name="Costo a crédito")),
            ],
            options={
                "verbose_name": "Cohorte",
                "verbose_name_plural": "Cohortes",
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dues_number", models.IntegerField()),
                ("balance", models.FloatField()),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mensualidades.cohort",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convenio de Pago",
                "verbose_name_plural": "Convenios de Pagos",
            },
        ),
        migrations.DeleteModel(
            name="PaymentAgreement",
        ),
        migrations.RemoveField(
            model_name="course",
            name="credit_cost",
        ),
        migrations.RemoveField(
            model_name="course",
            name="effective_cost",
        ),
        migrations.RemoveField(
            model_name="course",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="course",
            name="initial_date",
        ),
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Imagen"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.CharField(max_length=300, verbose_name="Dirección"),
        ),
        migrations.AlterField(
            model_name="student",
            name="cellphone",
            field=models.CharField(max_length=15, verbose_name="Celular"),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_names",
            field=models.CharField(max_length=150, verbose_name="Nombres"),
        ),
        migrations.AlterField(
            model_name="student",
            name="identification",
            field=models.CharField(max_length=13, verbose_name="Cédula"),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_names",
            field=models.CharField(max_length=150, verbose_name="Apellidos"),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mensualidades.student"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="enrollment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mensualidades.enrollment",
            ),
            preserve_default=False,
        ),
    ]
