# Generated by Django 4.1.3 on 2022-11-27 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mensualidades", "0002_cohort_enrollment_delete_paymentagreement_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cohort",
            options={"verbose_name": "Cohorte", "verbose_name_plural": "2. Cohortes"},
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Curso", "verbose_name_plural": "1. Cursos"},
        ),
        migrations.AlterModelOptions(
            name="enrollment",
            options={
                "verbose_name": "Matrícula",
                "verbose_name_plural": "3. Matrículas",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Pago", "verbose_name_plural": "5. Pagos"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "verbose_name": "Estudiante",
                "verbose_name_plural": "4. Estudiantes",
            },
        ),
        migrations.AddField(
            model_name="cohort",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mensualidades.course",
            ),
            preserve_default=False,
        ),
    ]
