# Generated by Django 4.1.3 on 2022-11-27 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mensualidades", "0003_alter_cohort_options_alter_course_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="course",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mensualidades.student",
                verbose_name="Estudiante",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cohort",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mensualidades.course",
                verbose_name="Curso",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="cohort",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mensualidades.cohort",
                verbose_name="Cohorte",
            ),
        ),
    ]
