# Generated by Django 4.1.3 on 2022-11-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mensualidades", "0004_remove_enrollment_course_enrollment_student_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "cohort")},
        ),
    ]
