# Generated by Django 4.1.3 on 2022-11-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mensualidades", "0006_alter_course_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="discount",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="payment_day",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="balance",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Saldo pendiente"
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="dues_number",
            field=models.IntegerField(verbose_name="Cuotas"),
        ),
    ]
