# Generated by Django 4.1.3 on 2022-12-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mensualidades",
            "0008_enrollment_initial_payment_alter_enrollment_discount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Pagado"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="dues_number",
            field=models.PositiveIntegerField(verbose_name="Cuotas"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="initial_payment",
            field=models.FloatField(default=0, verbose_name="Pago Inicial"),
        ),
    ]
